"""initial schema: files, assets, chunks

Revision ID: 5145bf773d94
Revises: 
Create Date: 2026-08-20 18:58:51.275589
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5145bf773d94'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.Enum('PDF', 'DOCX', 'IMAGE', name='filekind', native_enum=False), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'EXTRACTING', 'EXTRACTED', 'PROCESSING', 'READY', 'FAILED', name='processingstatus', native_enum=False), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='ck_files_size_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_sha256'), ['sha256'], unique=True)
        batch_op.create_index(batch_op.f('ix_files_status'), ['status'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('PAGE_IMAGE', 'EMBEDDED_IMAGE', 'SOURCE_IMAGE', 'THUMBNAIL', name='assetkind', native_enum=False), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('clip_embedded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'kind', 'ordinal', name='uq_assets_file_kind_ordinal')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_clip_embedded'), ['clip_embedded'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_file_id'), ['file_id'], unique=False)

    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('TEXT', 'OCR', 'CAPTION', name='chunkkind', native_enum=False), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('text_embedded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('char_count >= 0', name='ck_chunks_char_count_nonneg'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'kind', 'ordinal', name='uq_chunks_file_kind_ordinal')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_text_embedded'), ['text_embedded'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_text_embedded'))
        batch_op.drop_index(batch_op.f('ix_chunks_kind'))
        batch_op.drop_index(batch_op.f('ix_chunks_file_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_asset_id'))

    op.drop_table('chunks')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_file_id'))
        batch_op.drop_index(batch_op.f('ix_assets_clip_embedded'))

    op.drop_table('assets')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_status'))
        batch_op.drop_index(batch_op.f('ix_files_sha256'))
        batch_op.drop_index(batch_op.f('ix_files_kind'))

    op.drop_table('files')
    # ### end Alembic commands ###
