"""mark low-information chunks unsearchable

Revision ID: 6498ef634333
Revises: 5145bf773d94
Create Date: 2026-08-21 00:13:04.091844
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '6498ef634333'
down_revision: str | None = '5145bf773d94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        # server_default is required, not optional: the model's Python-side
        # default only applies to rows this process creates, so a NOT NULL
        # column added to a table that already has rows fails outright --
        # "Cannot add a NOT NULL column with default value NULL". Autogenerate
        # does not add it, and an empty test database never exercises the path.
        #
        # Existing chunks default to searchable; `ml.maintenance.reclassify_chunks`
        # re-evaluates them at startup and demotes the ones that no longer
        # qualify, so nothing is silently mis-marked.
        batch_op.add_column(
            sa.Column(
                'searchable',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
        batch_op.create_index(batch_op.f('ix_chunks_searchable'), ['searchable'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_searchable'))
        batch_op.drop_column('searchable')

    # ### end Alembic commands ###
